import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import ContactForm from "@/components/contact-form";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${inter.className} bg-[#0E332A] text-gray-950 relative sm:dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90 overflow-x-hidden`}>
        <div className="bg-[#fbe2e3] absolute top-[-6rem] -z-10 right-[11rem] h-[20rem] w-[20rem] rounded-full blur-[15rem] sm:w-[68.75rem] dark:bg-[#946263]"></div>
        <Header />
        {children}
        <ContactForm />
        <Toaster />
      </body>
    </html>
  );
}
